import { Types } from "../../shared/js/gametypes";

var Properties: any = {
  rat: {
    drops: {
      flask: 45,
      firefoxpotion: 5,
      scrollupgradelow: 20,
      ringbronze: 5,
      gold: 25,
    },
    hp: 20,
    armor: 0.5,
    weapon: 0.5,
  },
  crab: {
    drops: {
      flask: 20,
      axe: 10,
      shieldwood: 10,
      leatherarmor: 10,
      firefoxpotion: 5,
      scrollupgradelow: 15,
      ringbronze: 5,
      beltleather: 10,
      gold: 15,
    },
    hp: 60,
    armor: 2,
    weapon: 1,
  },
  bat: {
    drops: {
      flask: 25,
      axe: 15,
      firefoxpotion: 5,
      scrollupgradelow: 15,
      ringbronze: 5,
      beltleather: 10,
      shieldwood: 10,
      gold: 15,
    },
    hp: 80,
    armor: 2,
    weapon: 1,
  },
  goblin: {
    drops: {
      flask: 20,
      leatherarmor: 10,
      axe: 10,
      firefoxpotion: 5,
      scrollupgradelow: 5,
      scrollupgrademedium: 10,
      ringbronze: 5,
      beltleather: 10,
      shieldiron: 5,
      gold: 15,
    },
    hp: 90,
    armor: 2,
    weapon: 1,
  },
  wizard: {
    drops: {
      flask: 50,
      platearmor: 20,
      firefoxpotion: 5,
    },
    hp: 100,
    armor: 2,
    weapon: 6,
  },
  skeleton: {
    drops: {
      flask: 25,
      mailarmor: 10,
      axe: 15,
      firefoxpotion: 5,
      scrollupgrademedium: 10,
      ringbronze: 5,
      beltleather: 10,
      shieldiron: 5,
      gold: 15,
    },
    hp: 115,
    armor: 2,
    weapon: 2,
  },
  ogre: {
    drops: {
      flask: 25,
      platearmor: 15,
      firefoxpotion: 5,
      scrollupgrademedium: 13,
      ringbronze: 5,
      ringsilver: 2,
      shieldplate: 5,
      gold: 15,
    },
    hp: 250,
    armor: 3,
    weapon: 3,
  },
  snake: {
    drops: {
      flask: 30,
      mailarmor: 10,
      firefoxpotion: 5,
      scrollupgradelow: 5,
      scrollupgrademedium: 13,
      ringbronze: 5,
      ringsilver: 2,
      shieldiron: 5,
      gold: 15,
    },
    hp: 165,
    armor: 3,
    weapon: 3,
  },
  skeleton2: {
    drops: {
      flask: 25,
      platearmor: 10,
      bluesword: 10,
      firefoxpotion: 5,
      scrollupgrademedium: 15,
      ringsilver: 2,
      shieldplate: 5,
      gold: 12,
    },
    hp: 220,
    armor: 3,
    weapon: 3,
  },
  eye: {
    drops: {
      flask: 35,
      redarmor: 12,
      firefoxpotion: 5,
      scrollupgrademedium: 15,
      ringsilver: 4,
      beltplated: 3,
      amuletsilver: 2,
      shieldred: 5,
      gold: 12,
    },
    hp: 240,
    armor: 4,
    weapon: 3,
  },
  spectre: {
    drops: {
      flask: 35,
      redsword: 15,
      firefoxpotion: 5,
      scrollupgrademedium: 15,
      ringsilver: 4,
      beltplated: 3,
      amuletsilver: 2,
      shieldred: 5,
      gold: 12,
    },
    hp: 250,
    armor: 2,
    weapon: 4,
  },
  deathknight: {
    drops: {
      burger: 55,
      ringsilver: 5,
      beltplated: 5,
      amuletsilver: 2,
      scrollupgrademedium: 10,
      shieldred: 5,
      gold: 12,
    },
    hp: 275,
    armor: 4,
    weapon: 5,
  },
  boss: {
    drops: {
      goldensword: 70,
      skeletonkingcage: 30,
    },
    hp: 1200,
    armor: 6,
    weapon: 7,
  },
  rat2: {
    drops: {
      rejuvenationpotion: 70,
      bluearmor: 5,
      scrollupgradehigh: 5,
      shieldblue: 3,
      gold: 10,
    },
    hp: 240,
    armor: 7,
    weapon: 5,
  },
  bat2: {
    drops: {
      rejuvenationpotion: 60,
      blueaxe: 5,
      beltfrozen: 3,
      scrollupgradehigh: 5,
      shieldblue: 3,
      gold: 10,
    },
    hp: 280,
    armor: 6,
    weapon: 6,
  },
  goblin2: {
    drops: {
      rejuvenationpotion: 70,
      blueaxe: 5,
      beltfrozen: 5,
      scrollupgradehigh: 5,
      amuletgold: 1,
      shieldblue: 3,
      gold: 10,
    },
    hp: 240,
    armor: 5,
    weapon: 6,
  },
  werewolf: {
    drops: {
      rejuvenationpotion: 65,
      scrollupgradehigh: 5,
      bluearmor: 3,
      bluemorningstar: 3,
      beltfrozen: 3,
      ringgold: 2,
      amuletgold: 1,
      shieldblue: 3,
      gold: 10,
    },
    hp: 375,
    armor: 6,
    weapon: 7,
  },
  yeti: {
    drops: {
      rejuvenationpotion: 70,
      bluearmor: 3,
      bluemorningstar: 3,
      scrollupgradehigh: 5,
      ringgold: 3,
      shieldhorned: 2,
      gold: 10,
    },
    hp: 420,
    armor: 8,
    weapon: 8,
  },
  skeleton3: {
    drops: {
      rejuvenationpotion: 70,
      scrollupgradehigh: 5,
      hornedarmor: 3,
      belthorned: 1,
      ringgold: 2,
      amuletgold: 1,
      shieldhorned: 2,
      gold: 10,
    },
    hp: 420,
    armor: 8,
    weapon: 9,
  },
  skeletoncommander: {
    drops: {
      scrollupgradehigh: 5,
      belthorned: 1,
      hornedarmor: 5,
      ringgold: 4,
      amuletgold: 3,
      shieldhorned: 3,
    },
    hp: 2500,
    armor: 12,
    weapon: 12,
  },
  snake2: {
    drops: {
      rejuvenationpotion: 65,
      beltfrozen: 1,
      belthorned: 3,
      scrollupgradehigh: 5,
      ringgold: 3,
      amuletgold: 2,
      shieldhorned: 2,
      shieldfrozen: 2,
      gold: 10,
    },
    hp: 420,
    armor: 8,
    weapon: 10,
  },
  wraith: {
    drops: {
      rejuvenationpotion: 60,
      beltfrozen: 3,
      belthorned: 1,
      shieldhorned: 1,
      shieldfrozen: 2,
      scrollupgradehigh: 5,
      ringgold: 3,
      amuletgold: 2,
      gold: 10,
    },
    hp: 575,
    armor: 10,
    weapon: 11,
  },
  zombie: {
    drops: {
      rejuvenationpotion: 60,
      scrollupgradehigh: 3,
      ringgold: 2,
      amuletgold: 2,
      shieldfrozen: 1,
      gold: 10,
    },
    hp: 305,
    armor: 6,
    weapon: 12,
  },
  necromancer: {
    drops: {
      necromancerheart: 40,
      scrollupgradehigh: 4,
      ringgold: 4,
      amuletgold: 4,
      shieldfrozen: 4,
      ringnecromancer: 1,
    },
    hp: 3000,
    armor: 13,
    weapon: 13,
  },
  cow: {
    drops: {
      rejuvenationpotion: 40,
      hornedarmor: 1,
      frozenarmor: 1,
      frozensword: 1,
      beltfrozen: 1,
      belthorned: 1,
      shieldhorned: 1,
      shieldfrozen: 1,
      ringgold: 1,
      amuletgold: 1,
      scrollupgradehigh: 1,
      gold: 10,
    },
    hp: 600,
    armor: 16,
    weapon: 20,
  },
  cowking: {
    drops: {
      diamondsword: 8,
      diamondarmor: 8,
      beltdiamond: 8,
      shielddiamond: 8,
      amuletcow: 5,
      scrolltransmute: 5,
      cowkinghorn: 20,
      scrollupgradehigh: 37,
    },
    hp: 6_500,
    armor: 22,
    weapon: 24,
  },
  minotaur: {
    drops: {
      ringminotaur: 5,
      scrolltransmute: 5,
      minotauraxe: 10,
      beltminotaur: 10,
      scrollupgradehigh: 69,
    },
    hp: 12_500,
    armor: 29,
    weapon: 32,
  },
  rat3: {
    drops: {
      powdergreen: 5,
      rejuvenationpotion: 25,
      poisonpotion: 25,
      scrollupgradelegendary: 3,
      amuletplatinum: 2,
      ringplatinum: 2,
      emeraldsword: 2,
      emeraldarmor: 2,
      beltemerald: 2,
      shieldemerald: 2,
      gold: 10,
    },
    hp: 600,
    armor: 16,
    weapon: 14,
  },
  oculothorax: {
    drops: {
      rejuvenationpotion: 30,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      executionersword: 1,
      executionerarmor: 1,
      beltexecutioner: 1,
      shieldexecutioner: 1,
      emeraldsword: 1,
      emeraldarmor: 1,
      beltemerald: 1,
      shieldemerald: 1,
      gold: 12,
    },
    hp: 1100,
    armor: 22,
    weapon: 23,
  },
  kobold: {
    drops: {
      rejuvenationpotion: 30,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      executionersword: 2,
      executionerarmor: 2,
      beltexecutioner: 2,
      shieldexecutioner: 2,
      gold: 12,
    },
    hp: 1300,
    armor: 24,
    weapon: 26,
  },
  golem: {
    drops: {
      rejuvenationpotion: 30,
      scrollupgradelegendary: 5,
      ringplatinum: 3,
      amuletplatinum: 3,
      executionersword: 1,
      executionerarmor: 1,
      beltexecutioner: 1,
      shieldexecutioner: 1,
      emeraldsword: 1,
      emeraldarmor: 1,
      beltemerald: 1,
      shieldemerald: 1,
      gold: 15,
    },
    hp: 1600,
    armor: 25,
    weapon: 23,
  },
  snake3: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      executionersword: 2,
      executionerarmor: 2,
      beltexecutioner: 2,
      shieldexecutioner: 2,
      gold: 10,
    },
    hp: 950,
    armor: 21,
    weapon: 25,
  },
  snake4: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      executionersword: 1,
      executionerarmor: 1,
      beltexecutioner: 1,
      shieldexecutioner: 1,
      dragonsword: 1,
      dragonarmor: 1,
      shielddragon: 1,
      gold: 10,
    },
    hp: 950,
    armor: 21,
    weapon: 25,
  },
  skeleton4: {
    drops: {
      rejuvenationpotion: 25,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      templarsword: 2,
      templararmor: 2,
      belttemplar: 2,
      shieldtemplar: 2,
      gold: 10,
    },
    hp: 1150,
    armor: 23,
    weapon: 24,
  },
  ghost: {
    drops: {
      rejuvenationpotion: 15,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      dragonsword: 2,
      dragonarmor: 2,
      shielddragon: 2,
      gold: 12,
    },
    hp: 1400,
    armor: 24,
    weapon: 26,
  },
  skeletonberserker: {
    drops: {
      rejuvenationpotion: 25,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      templarsword: 2,
      templararmor: 2,
      belttemplar: 2,
      shieldtemplar: 2,
      gold: 12,
    },
    hp: 1200,
    armor: 22,
    weapon: 24,
  },
  skeletontemplar: {
    drops: {
      powderblack: 100,
    },
    hp: 4500,
    armor: 30,
    weapon: 25,
  },
  skeletontemplar2: {
    drops: {
      powderblue: 100,
    },
    hp: 4500,
    armor: 30,
    weapon: 25,
  },
  spider: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      poisonpotion: 10,
      dragonsword: 2,
      dragonarmor: 2,
      shielddragon: 2,
      gold: 12,
    },
    hp: 1440,
    armor: 24,
    weapon: 24,
  },
  spider2: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      poisonpotion: 10,
      dragonsword: 2,
      dragonarmor: 2,
      shielddragon: 2,
      gold: 12,
    },
    hp: 1440,
    armor: 24,
    weapon: 24,
  },
  spiderqueen: {
    drops: {
      scrollupgradelegendary: 10,
      ringplatinum: 5,
      amuletplatinum: 5,
      poisonpotion: 33,
      dragonsword: 5,
      dragonarmor: 5,
      shielddragon: 5,
    },
    hp: 8500,
    armor: 32,
    weapon: 26,
  },
  skeletonarcher: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 3,
      amuletplatinum: 3,
      gold: 12,
    },
    hp: 1140,
    armor: 20,
    weapon: 28,
  },
  butcher: {
    drops: {
      soulstone: 100,
    },
    hp: 10_000,
    armor: 36,
    weapon: 32,
  },
  wraith2: {
    drops: {
      rejuvenationpotion: 20,
      scrollupgradelegendary: 4,
      ringplatinum: 3,
      amuletplatinum: 3,
      moonsword: 3,
      moonarmor: 3,
      beltmoon: 3,
      shieldmoon: 3,
      gold: 12,
    },
    hp: 1620,
    armor: 28,
    weapon: 26,
  },
  mage: {
    drops: {
      rejuvenationpotion: 15,
      scrollupgradelegendary: 4,
      ringplatinum: 2,
      amuletplatinum: 2,
      moonsword: 3,
      moonarmor: 3,
      beltmoon: 3,
      shieldmoon: 3,
      gold: 12,
    },
    hp: 1210,
    armor: 22,
    weapon: 26,
  },
  templeMob: {
    drops: {
      rejuvenationpotion: 15,
      scrollupgradelegendary: 4,
      mysticalsword: 2,
      mysticalarmor: 2,
      beltmystical: 2,
      shieldmystical: 2,
      ringmystical: 1,
      gold: 12,
    },
  },
  shaman: {
    drops: {
      scrollupgradelegendary: 50,
      ringplatinum: 3,
      amuletplatinum: 3,
      moonsword: 5,
      moonarmor: 5,
      beltmoon: 5,
      shieldmoon: 5,
      ringwizard: 1,
      ringmystical: 1,
    },
    hp: 12_000,
    armor: 32,
    weapon: 30,
  },
  worm: {
    drops: {
      powdergold: 100,
    },
    hp: 15_000,
    armor: 32,
    weapon: 33,
  },
  deathangel: {
    drops: {
      scrollupgradelegendary: 76,
      mysticalsword: 5,
      mysticalarmor: 5,
      beltmystical: 5,
      shieldmystical: 5,
      ringmystical: 2,
    },
    hp: 20_000,
    armor: 34,
    weapon: 40,
  },
};

Properties.getArmorLevel = function (kind) {
  try {
    if (Types.isMob(kind)) {
      return Properties[Types.getKindAsString(kind)].armor;
    } else {
      return Types.getArmorRank(kind) + 1;
    }
  } catch (err) {
    console.error("No level found for armor: " + Types.getKindAsString(kind));
    console.error("Error stack: " + err.stack);
  }
};

Properties.getWeaponLevel = function (kind) {
  try {
    if (Types.isMob(kind)) {
      return Properties[Types.getKindAsString(kind)].weapon;
    } else {
      return Types.getWeaponRank(kind) + 1;
    }
  } catch (err) {
    console.error("No level found for weapon: " + Types.getKindAsString(kind));
    console.error("Error stack: " + err.stack);
  }
};

Properties.getHitPoints = function (kind) {
  return Properties[Types.getKindAsString(kind)].hp;
};
Properties.getExp = function (kind) {
  return Properties[Types.getKindAsString(kind)].exp;
};

export default Properties;
